### ISSUE TITLE
UI/UX issues

### ISSUE THREAD

**Issue by tomvachon** [RiotGames/cloud-inquisitor#48]
1. When the SQS scheduler is disabled (as is by default). The logs spew that its missing.  Its defaulted as the scheduler in the config, that should be changed or the error should be updated.

2. (Known) Enabled plugins after install require python manage.py setup to rerun

3. An install should be minimally functional at start (e.g. use local scheduler, local auth, etc) as a base set of plugins to cut down on the SNR for people kicking the tires

4. Changing parameters of the SQS Scheduler required a full restart of the supervisor'ed processes or it gave back cryptic "WSDL" errors

5. IAM permission errors on non-core installs (e.g. ec2 describe instances") is silently ignored in the UI unlike s3:ListBuckets which fails loudly

**Comment by tomvachon** [comment]
Item 1 is fixed by #57
Item 3 is fixed by #57 
Item 4 was likely do to a bad restart

This leases only Items 2 and Items 5 left

**Comment by TheM0ng00se** [comment]
Is 2. still an issue with the most recent branch? Plugins now all come installed by default.

**Comment by tomvachon** [comment]
No, its a documentation issue when more plugins are developed though

**Comment by TheM0ng00se** [comment]
2 is fixed now and 5 we likely won't fix.
